### ISSUE TITLE
Cross browser testing

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-facebook#27]
- [x] Cross-browser testing
- [x] Performance
- [x] How does it all work on mobile?

**Comment by pauldwaite** [comment]
The prototype user journey may be useful for this: https://github.com/wearethoughtfox/amnesty-facebook/issues/30

**Comment by pauldwaite** [comment]
- [x] Edge, Windows 10
- [x] IE 11, Windows 8
- [x] IE 10, Windows 7 (**odd background image issue**  #42 )
- [x] IE 9, Windows 7 (**the app doesn’t work** #43 )
- [x] Safari latest, macOS 10.12 latest
- [x] Chrome latest, macOS 10.12 latest
- [x] Firefox latest, macOS 10.12 latest
- [x] Safari, iOS latest, iPhone
- [ ] Safari, iOS 9, iPhone?
- [x] Safari, iOS latest, iPad
- [x] Chrome 55, Android 7 (Google Pixel latest)
- [x] Android browser, Samsung Galaxy S4, Android 4.something
- [ ] Other Androids?

**Comment by pauldwaite** [comment]
Bugs found:

- [x] #46 (When nominating another person, the first nominee’s message is re-posted)
- [x] #38 (Edge logs some console errors for XHR 404s)
- [x] #52 (iPad: Amnesty website iframe extends past the bottom of the background image)
- [ ] #50 (iOS Safari: “Nominate another person” button is translucent)
- [x] #49 (Dave Alagjahhfehji Bharambesky throws an error for some reason)
- [x] #43 (IE 9: list of friends does not appear)
- [x] #42 (IE 10: after loading the friends list or posting a message, the background goes weird)
- [x] #37 (The next and previous buttons look awfully big in IE 11)
