### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-facebook#28]
- [x] RTL for Arabic - _not needed at this stage_
- [x] Match the hover on the button on the call to action embed?  

1. Friends list
- [ ] Background image jumps slightly because scroll bar _could_ be added
- [x] Handle / manipulate scroll, e.g. scroll to top, of friends list on pagination or not? _I think this is best without_
- [x] Next / previous jumps around and moves on show/hide
- [x] Pagination links aren’t updated after clicking the “Nominate another person” button

2. Buttons/links
- [x] Mouse cursor turns to text selection when hovering links/buttons (#35)
- [x] There’s no visual indication when buttons are pressed (#44)

3. Posting messages
- [x] There’s no visual indication that we’re waiting for the Facebook API (#45)

**Comment by pauldwaite** [comment]
> Pagination links aren’t updated after clicking the “Nominate another person” button

This might fix it: https://github.com/wearethoughtfox/amnesty-facebook/compare/fix-pagination-after-nominate-again?expand=1

**Comment by robertocarroll** [comment]
That got it, thanks!

**Comment by robertocarroll** [comment]
The UI is a bit clunky at the moment. What can we do to make it feel a bit slicker? Transitions? Animations? Or do they all come at a cost (performance)?

**Comment by robertocarroll** [comment]
Closing unless we hear anything back from client.
